In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings

warnings.filterwarnings('ignore')

In [2]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'youtube'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

youtube_df = pd.read_sql_query('select * from youtube',con=engine)

# no need for an open connection,
# as we're only doing a single query
engine.dispose()

In [3]:
youtube_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
Rank             5000 non-null object
Grade            5000 non-null object
Channel name     5000 non-null object
Video Uploads    5000 non-null object
Subscribers      5000 non-null object
Video views      5000 non-null int64
dtypes: int64(1), object(5)
memory usage: 136.8+ KB

In [4]:
# print first rows of the data frame
youtube_df.head()

,Rank,Grade,Channel name,Video Uploads,Subscribers,Video views
0,1st,A++,Zee TV,82757,18752951,20869786591
1,2nd,A++,T-Series,12661,61196302,47548839843
2,3rd,A++,Cocomelon - Nursery Rhymes,373,19238251,9793305082
3,4th,A++,SET India,27323,31180559,22675948293
4,5th,A++,WWE,36756,32852346,26273668433

In [5]:
youtube_df[(youtube_df["Video Uploads"].str.strip() == "--") | (youtube_df["Subscribers"].str.strip() == "--")]

,Rank,Grade,Channel name,Video Uploads,Subscribers,Video views
17,18th,A+,Vlad and Nikita,53,--,1428274554
108,109th,A,BIGFUN,373,--,941376171
115,116th,A,Bee Kids Games - Children TV,740,--,414535723
142,143rd,A,ChiChi TV Siêu Nhân,421,--,2600394871
143,144th,A,MusicTalentNow,1487,--,3252752212
152,153rd,A,Family GamesTV,282,--,1287242549
156,157th,A,KH Show,31,--,106302038
175,176th,A,LES BOYS TV2,116,--,387595623
180,181st,A,BIBO TOYS,313,--,1574657579
189,190th,A,Kids Tv Show,8,--,86516866
192,193rd,A,Happy Funny Kids Toys Pretend Play,850,--,1778372917
197,198th,A,Learn Colors Keiki,6,--,89116512
209,210th,A,Ly LY ToysReview,33,--,90941513
213,214th,A,Beat chất lượng cao,563,--,622132999
223,224th,A,Purana Hindustan,91,--,501921413
230,231st,A,Happy Lives,188,--,515722472
234,235th,A,Salih Reis'in Dünyası,237,--,2197191069
235,236th,A,News ThatMatter,365,--,77361248
238,239th,A,PlayGammer100,7,--,261227
253,254th,A,Flipkart,604,--,718345351
255,256th,A,Los Juguetes BB,114,--,82824448
267,268th,,MidnightXChannel,--,--,190256974
291,292nd,A,Sham Drama شام دراما,6494,--,885923365
322,323rd,A,Ghiền Phim Hàn,854,--,1072407139
326,327th,A,Bollywood Event Talkies,10,--,350
346,347th,A,Jhankar Station 07,205,--,78360362
357,358th,A,Purani Kahani,66,--,205282926
382,383rd,A,El Blog del Narco,4449,--,70680037
391,392nd,A,apple kids,70,--,370257049
392,393rd,A,DLS News,1579,--,514253195
...,...,...,...,...,...,...
4645,"4,646th",B+,Bangla Gorom News,1896,--,151760154
4653,"4,654th",B+,Fingerwager,22,--,119546477
4657,"4,658th",B+,knowledge master,806,--,248868112
4663,"4,664th",B+,PTV Cricket,1351,--,132162672
4668,"4,669th",B+,TTV BTW,69,--,11325628
4687,"4,688th",B+,عالم الإبداع - Creative…,216,--,145773941
4690,"4,691st",B+,Tizcall,68,--,108495917
4695,"4,696th",B+,My Tam,264,--,538371669
4704,"4,705th",B+,Louie Rochester,73,--,75536179
4715,"4,716th",B+,Mickey Baby Tv,47,--,39117306
4730,"4,731st",B+,Perfect Life,263,--,156462604
4748,"4,749th",B+,Samsung South Africa,311,--,96264871
4771,"4,772nd",B+,العالمية للترفية HD,231,--,36001078
4786,"4,787th",B+,Justin Wright S.,458,--,289623382
4802,"4,803rd",B+,News Now,4234,--,240258091
4822,"4,823rd",B+,مشاهيرنا,350,--,51775617
4836,"4,837th",B+,CARS 4 KIDS,478,--,1643267574
4844,"4,845th",B+,Khatulistiwa Record,132,--,153432783
4886,"4,887th",B+,Xpose News,40476,--,204810831
4892,"4,893rd",B+,Everything For U,184,--,69313209
4893,"4,894th",B+,VB Musicas,71,--,48275804
4895,"4,896th",B+,Totoykids Explorer,165,--,363738234
4898,"4,899th",,ExzoticSlice,--,99785,9745292
4912,"4,913th",B+,اخترنا لك,775,--,95271752
4936,"4,937th",B+,李婶儿说电影,139,--,53572147
4941,"4,942nd",B+,GMTV,183,--,127080542
4948,"4,949th",B+,Keivon ToysReview,468,--,481568513
4956,"4,957th",B+,CLICKNEWS,2661,--,139940815
4961,"4,962nd",B+,ONE Championship,905,--,109836654
4990,"4,991st",B+,Ho Ngoc Ha's Official Channel,208,--,127185704

In [6]:
youtube_df.nunique()

Rank             5000
Grade               6
Channel name     4993
Video Uploads    2286
Subscribers      4612
Video views      5000
dtype: int64

In [12]:
# this method returns group numbers
# given video views
def categorize_video_views(views_num):
    if views_num >= 1000000000:
        return 1
    elif views_num >= 100000000:
        return 2
    else:
        return 3

# we use Pandas' .apply() method by calling the function above.
youtube_df['views_group'] = youtube_df['Video views'].apply(categorize_video_views)

# let's see how many observations we have in each group
print(youtube_df.groupby("Grade")["Video views"].sum())

Grade
A       2273948590311
A+       248177945463
A++      211990911928
A-      1066136831368
B+      1556398001373
            594720307
Name: Video views, dtype: int64